### ISSUE TITLE
Addressing W3C TAG feedback 

### ISSUE THREAD

**Issue by majido** [WICG/overscroll-behavior#22]
W3C TAG has provided [feedback](https://github.com/w3ctag/design-reviews/issues/193#issuecomment-332547145) on this proposal. 

There are a few suggestions. Let's use this issue to go over them and work out the best solution and how and if they should influence the design of this API. Here are the three points raised:

* Are there events that allow a page to detect and act on overscroll behavior? (perhaps a separate point, but worth looking into)
* Should this be a new property, or should this be a new part of the value on 'overflow'? It wasn't clear to us which is the right thing; in CSS this is often decided by whether the pieces should cascade together or separately.
* Another related question is whether there should be logical (inline-direction and block-direction rather than x and y) versions of these -- and also whether there should be logical versions of overflow-x and overflow-y. https://drafts.csswg.org/css-logical/ doesn't have those, though.

**Comment by majido** [comment]
Here is some initial thinking about these.

*Are there events that allow a page to detect and act on overscroll behavior? (perhaps a separate point, but worth looking into)*
**Response**: No currently there is no event that covers overscroll but this CSS property is complementary to something like that and does not preclude it. We have chose to focus our
effort on CSS property first as it does not require implementors to expose performance 
sensitive machinery such as scrolling to new blocking events.  
There is already a [scroll customization effort](https://github.com/w3c/css-houdini-drafts/blob/master/scroll-customization-api/explainer.md) that aims to create low-level primitive that explain scrolling. I think that already has some hooks for overscroll and it is a more appropriate venue to explore the idea of adding an event if there is enough interest.

*Should this be a new property, or should this be a new part of the value on 'overflow'? It wasn't clear to us which is the right thing; in CSS this is often decided by whether the pieces should cascade together or separately.*
**My Initial thoughts**: I am actually not sure I fully understand this.

If "separate cascade" refers to the ability to have css rules where we set only one property and not the other, then I can imagine situations where this is needed for SBB (scroll-boundary-behavior). For example a p2r component is only interested in controlling the SBB but does not need to control the overflow. Or perhaps a page wants to set SBB for all scrollers to be contain using a *{} rule but not necessarily want to control the overflow. 
We have the precedent of “scroll-behavior” here which is an independent property that plays a similar role as scroll-boundary-behavior. I am not able to find the rationale for that though. 

Is there any ideas to do one vs the other?

*Another related question is whether there should be logical (inline-direction and block-direction rather than x and y) versions of these -- and also whether there should be logical versions of overflow-x and overflow-y. https://drafts.csswg.org/css-logical/ doesn't have those, though.*
**Response**: `scroll-boundary-behavior-{x,y}` was chosen to match `overflow-{x,y}`. I think it is reasonable to have logical directions but we should add those in conjunction of adding them to overflow supports them.

**Comment by bgirard** [comment]
Sorry for the delay. I'm on paternity leave with a new born and just moved but I'd like for this to continue moving forward.

I fully agree with your responses. I feel very strongly that its much cleaner for it to cascade separately from the overflow if I understand that point correctly. I'm the most worried about any existing CSS  selector that has an overflow value in a large code base. To make sure you get the proper SBB you have to make sure that every selector that is setting the overflow value that might have a higher specificity does not clobber your SBB value. Similarly for any JS call site that is updating `style.overflow` will now reset the SBB value.

**Comment by majido** [comment]
Paternity leave :fireworks:. Congratulations, that is awesome. I will make sure this is moving forward specially that we plan to ship it soon. :)

Thanks for that example. I was not even considering the implication this would have when dealing with a large code base that has assumption builtin around the behavior of `overflow`.

**Comment by majido** [comment]
W3C tag review is [complete](https://github.com/w3ctag/design-reviews/issues/193#issuecomment-346964139). The result is that TAG generally approved it. Here is the full response: 

> Discussed in out 2017-11-21 telcon and generally approved. Our primary concern at this point is where this fits in to Houdini scrolling APIs, e.g. how can this behavior be explained in terms of the lower-level API? how does the scrolling API provide the missing pieces to implement functionality like "pull-to-refresh"? We accept this property is but one part of a larger picture, we just want to see the rest...

There meeting notes are also public if anyone is interested.
