### ISSUE TITLE
block scroll-chaning even if it has no scrollbars

### ISSUE THREAD

**Issue by nuxodin** [WICG/overscroll-behavior#30]
Is it possible to extend the spec with a property-value that blocks scroll-chaning event if it is only a potentially scrollabel element?

I know that this behaviour has already been discussed and rejected. But in most cases it would definitely fit my needs better.

**Comment by majido** [comment]
Can you please clarify what you mean by `only a potentially scrollable element`?

The spec specifically allows any **scroll container** to have overscroll-behavior that takes effect. This covers any element with overflow `scroll`, `hidden`, and `auto`. In the case of `auto` the element may not be overflowing but overscroll-behavior gets applied. So `overflow:auto` is indeed a *potentially scrollable element*.

This was specifically discussed in issue #4 and approved.

Does this not work for you?

**Comment by nuxodin** [comment]
Ok, it seems to be a firefox bug.
It works in Chrome. 
See:
https://codepen.io/anon/pen/qJdPQB
