### ISSUE TITLE
Mention non-passive listener timeout as motivation under the introduction

### ISSUE THREAD

**Issue by bgirard** [WICG/overscroll-behavior#9]
If a browser must use non-passive event listeners it has to respond within 200-300ms otherwise browsers will timeout and allow the scroll. This can lead to inconsistent user experience as the scroll will sometimes be chained when the page is intermittently unresponsive.

**Comment by majido** [comment]
I feel the existing discussion about non passive event listener is good enough. 

> A non passive event listener will delay scrolling because the user agent will have to wait for the result of the event listener to determine if preventDefault was called causing increased scroll latency.

**Comment by bgirard** [comment]
Agreed
